name: global_amenities_trail
environment:
  sdk: ">=2.17.0 <3.0.0" # 專門對應 Zapp! 的 2.19.2 版本
dependencies:
  flutter:
    sdk: flutter
  flutter_map: 3.1.0
  latlong2: 0.8.1
  supabase_flutter: 1.10.0
flutter:
  uses-material-design: true
