name: global_amenities_trail
description: 藝文與友善設施 App
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0" # 確保符合 Zapp! 的 SDK 2.19.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: 3.1.0       # 穩定舊版地圖
  latlong2: 0.8.1
  supabase_flutter: 1.10.0 # 穩定舊版連線

flutter:
  uses-material-design: true
